[project]
name = "epub-verify"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "ebooklib>=0.20",
    "lxml>=6.0.2",
    "pillow>=12.1.0",
]
